services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: dw-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./apps/backend
    restart: always
    env_file: ./apps/backend/.env
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres

volumes:
  pgdata:
